name: Azure Static Web Apps CI/CD - ltorres-1 branch

on:
  push:
    branches:
      - ltorres-1
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - ltorres-1

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LTORRES_1 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: ""                    # No API needed for frontend-only
          output_location: ".next"            # Next.js output location
        env:
          # Add your environment variables for runtime
          SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SPORTRADAR_API_KEY: ${{ secrets.SPORTRADAR_API_KEY }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LTORRES_1 }}
          action: "close"
          app_location: "/frontend"