name: CI/CD - ltorres-1 Development Branch

on:
  push:
    branches: [ ltorres-1 ]
  pull_request:
    branches: [ ltorres-1 ]

jobs:
  frontend-checks:
    name: Frontend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript check
      run: npm run type-check
      continue-on-error: true

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Build frontend
      run: npm run build
      continue-on-error: true

  backend-checks:
    name: Backend Checks  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run backend tests
      run: npm test
      continue-on-error: true
      
    - name: Check backend syntax
      run: node -c src/server.js

  deployment-status:
    name: Deployment Status Check
    runs-on: ubuntu-latest
    needs: [frontend-checks, backend-checks]
    
    steps:
    - name: Deployment Info
      run: |
        echo "🎉 CI Checks Complete!"
        echo ""
        echo "📦 Free Stack Deployment Status:"
        echo "• Frontend: Auto-deploys to Netlify from ltorres-1 branch"
        echo "• Backend: Auto-deploys to Render from ltorres-1 branch"  
        echo "• Database: Supabase PostgreSQL (always available)"
        echo ""
        echo "💰 Cost: $0/month (down from $103/month)"
        echo "🔗 NFL Survivor system ready for development!"